const cfg=window.PROGRESS_CONFIG||{};let sb=null,currentUser=null,selectedDate=new Date();
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function dateKey(d){return new Date(d).toISOString().slice(0,10)}
function pct(actual,target,type){if(type==='boolean')return actual?100:0;return target>0?Math.round(actual/target*100):0}
async function profile(){if(!currentUser)return null;const {data,error}=await sb.from('profiles').select('*').eq('id',currentUser.id).single();if(error)return null;return data}
async function isAdmin(){const p=await profile();return p?.role==='admin'}
function setAuthTab(mode){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.auth===mode));$('loginForm').classList.toggle('hidden',mode!=='login');$('registerForm').classList.toggle('hidden',mode!=='register')}
async function boot(){if(!cfg.supabaseUrl||!cfg.supabasePublishableKey){$('configWarning').classList.remove('hidden');return}sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabasePublishableKey);const {data}=await sb.auth.getSession();if(data.session){currentUser=data.session.user;await enterApp()} }
async function enterApp(){const p=await profile();if(!p){toast('No se encontró el perfil.');return}if(!p.approved){await sb.auth.signOut();toast('Tu cuenta está pendiente de aprobación.');return} $('auth').classList.add('hidden');$('app').classList.remove('hidden');$('userName').textContent=p.username||'Usuario';$('userEmail').textContent=p.email||currentUser.email;$('avatar').textContent=(p.username||'U')[0].toUpperCase();const admin=p.role==='admin';document.querySelectorAll('.admin-only').forEach(x=>x.classList.toggle('hidden',!admin));showPage('home')}
$('loginForm').onsubmit=async e=>{e.preventDefault();const email=$('loginEmail').value.trim().toLowerCase(),password=$('loginPassword').value;const {data,error}=await sb.auth.signInWithPassword({email,password});if(error){toast('Correo o contraseña incorrectos.');return}currentUser=data.user;await enterApp()}
$('registerForm').onsubmit=async e=>{e.preventDefault();const username=$('regUsername').value.trim(),email=$('regEmail').value.trim().toLowerCase(),password=$('regPassword').value;const {data,error}=await sb.auth.signUp({email,password,data:{username}});if(error){toast(error.message);return}toast(data.session?'Cuenta creada. Queda pendiente de aprobación.':'Cuenta creada. Revisa tu correo si la confirmación está activada.');setAuthTab('login')}
$('logout').onclick=async()=>{await sb.auth.signOut();currentUser=null;$('app').classList.add('hidden');$('auth').classList.remove('hidden');setAuthTab('login')}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>setAuthTab(b.dataset.auth));document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
async function showPage(page){document.querySelectorAll('.page').forEach(p=>p.classList.add('hidden'));$(`page-${page}`).classList.remove('hidden');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.page===page));$('pageTitle').textContent={home:'Hoy',calendar:'Calendario',stats:'Estadísticas',profile:'Perfil',admin:'Administración'}[page];if(page==='home')await renderHome();if(page==='calendar')await renderCalendar();if(page==='stats')await renderStats();if(page==='profile')await renderProfile();if(page==='admin')await renderAdmin()}
async function getGoals(){const {data,error}=await sb.from('goals').select('*').eq('user_id',currentUser.id).eq('active',true).order('sort_order');if(error){toast(error.message);return[]}return data||[]}
async function getRecords(day){const {data}=await sb.from('daily_records').select('*').eq('user_id',currentUser.id).eq('date',day);return data||[]}
async function renderHome(){const day=dateKey(selectedDate),goals=await getGoals(),records=await getRecords(day);const map=Object.fromEntries(records.map(r=>[r.goal_id,r]));let applicable=goals.filter(g=>{const dow=new Date(day+'T12:00:00').getDay();return (g.weekdays||[0,1,2,3,4,5,6]).includes(dow)});let done=0,total=applicable.length;applicable.forEach(g=>{const r=map[g.id];if(r?.status==='completed')done++});const overall=total?Math.round(done/total*100):0;$('page-home').innerHTML=`<div class="hero"><div><p class="eyebrow">${new Date(day+'T12:00:00').toLocaleDateString('es-ES',{weekday:'long',day:'numeric',month:'long'})}</p><h1>Un día más. Un paso más.</h1><p>Completa tus objetivos y convierte tus datos diarios en una visión clara de tu progreso.</p></div><div class="ring" style="--pct:${overall}"><div><b>${overall}%</b><small>del día</small></div></div></div><div class="stats-row"><div class="stat"><b>${done}/${total}</b><span>Objetivos completados</span></div><div class="stat"><b>${records.filter(r=>r.status==='na').length}</b><span>No aplica hoy</span></div><div class="stat"><b>${applicable.length?Math.max(...applicable.map(g=>pct(map[g.id]?.actual||0,g.target,g.type)),0):0}%</b><span>Mejor objetivo del día</span></div></div><div class="week">${weekButtons(selectedDate)}</div><div class="section-head"><h3>Objetivos de hoy</h3><button class="add" onclick="addGoal()">+ Añadir objetivo</button></div><div class="goals">${applicable.map(g=>goalHTML(g,map[g.id])).join('')||'<div class="panel">Todavía no tienes objetivos para este día.</div>'}</div>`}
function weekButtons(d){let out='';for(let i=-1;i<=5;i++){let x=new Date(d);x.setDate(x.getDate()+i);let k=dateKey(x);out+=`<button class="day ${i===0?'active':''}" onclick="pickDate('${k}')"><b>${x.toLocaleDateString('es-ES',{weekday:'short'}).replace('.','')}</b><strong>${x.getDate()}</strong></button>`}return out}
function goalHTML(g,r){const actual=r?.actual??(g.type==='boolean'?false:0),p=pct(actual,g.target,g.type),status=r?.status||'pending';return `<div class="goal ${status==='completed'?'done':''}"><button class="check" onclick="toggleGoal('${g.id}',${status==='completed'?'false':'true'})" aria-label="completar"></button><div class="goal-name">${esc(g.name)}<div class="goal-target">Objetivo: ${g.type==='boolean'?'Sí':g.target+' '+esc(g.unit||'')} ${status==='na'?'· No aplica':''}</div></div><div class="goal-target">${g.type==='boolean'?(status==='completed'?'Hecho':'Pendiente'):(actual+' '+esc(g.unit||''))}</div><div class="pct">${status==='na'?'—':p+'%'}</div><button class="goal-actions" onclick="editGoal('${g.id}')">⋯</button></div>`}
window.pickDate=async k=>{selectedDate=new Date(k+'T12:00:00');await renderHome()};window.toggleGoal=async(id,complete)=>{const g=(await getGoals()).find(x=>x.id===id);if(!g)return;const day=dateKey(selectedDate),actual=g.type==='boolean'?complete:(await getRecords(day)).find(r=>r.goal_id===id)?.actual||0;const payload={user_id:currentUser.id,goal_id:id,date:day,actual,status:complete?'completed':'pending'};await sb.from('daily_records').upsert(payload,{onConflict:'user_id,goal_id,date'});await renderHome()};window.editGoal=async id=>{const g=(await getGoals()).find(x=>x.id===id);if(!g)return;const val=prompt(`Nuevo objetivo para ${g.name}:`,g.target);if(val===null)return;await sb.from('goals').update({target:g.type==='boolean'?1:Number(val)}).eq('id',id).eq('user_id',currentUser.id);await renderHome()};window.addGoal=async()=>{const name=prompt('Nombre del objetivo:');if(!name)return;const type=prompt('Tipo: boolean, time o quantity','quantity');if(!['boolean','time','quantity'].includes(type))return toast('Tipo no válido.');let target=1,unit='veces';if(type!=='boolean'){target=Number(prompt('Objetivo numérico:','1'));unit=prompt('Unidad (h, min, kg, g, ml, l, km, m, pasos, repeticiones, páginas, veces, unidades):','veces')||'veces'}await sb.from('goals').insert({user_id:currentUser.id,name,type,target,unit,weekdays:[0,1,2,3,4,5,6],sort_order:Date.now(),active:true});await renderHome()};
async function renderCalendar(){let base=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),1),year=base.getFullYear(),month=base.getMonth(),days=new Date(year,month+1,0).getDate(),start=(base.getDay()+6)%7;const goals=await getGoals();let rec=[];const {data}=await sb.from('daily_records').select('date,status').eq('user_id',currentUser.id).gte('date',`${year}-${String(month+1).padStart(2,'0')}-01`).lte('date',`${year}-${String(month+1).padStart(2,'0')}-${days}`);rec=data||[];let map={};for(const r of rec){map[r.date]??=[];map[r.date].push(r.status)}let cells='';for(let i=0;i<start;i++)cells+='<div></div>';for(let d=1;d<=days;d++){const k=`${year}-${String(month+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`,ss=map[k]||[];const cls=ss.includes('completed')?'green':ss.includes('pending')?'yellow':ss.includes('na')?'yellow':'red';cells+=`<button class="cal-day" onclick="pickDate('${k}')"><strong>${d}</strong><br><i class="dot ${cls}"></i></button>`}$('page-calendar').innerHTML=`<div class="calendar-card"><div class="section-head"><h3>${base.toLocaleDateString('es-ES',{month:'long',year:'numeric'})}</h3><div><button class="add" onclick="changeMonth(-1)">‹</button> <button class="add" onclick="changeMonth(1)">›</button></div></div><div class="calendar-grid">${['L','M','X','J','V','S','D'].map(x=>`<div class="cal-head">${x}</div>`).join('')}${cells}</div></div>`}window.changeMonth=async n=>{selectedDate=new Date(selectedDate.getFullYear(),selectedDate.getMonth()+n,1);await renderCalendar()};
async function renderStats(){const goals=await getGoals();const {data:records}=await sb.from('daily_records').select('*').eq('user_id',currentUser.id);const rs=records||[];$('page-stats').innerHTML=`<div class="panel"><div class="section-head"><h3>Rendimiento por objetivo</h3><span class="muted">Histórico guardado</span></div><div class="bars">${goals.map(g=>{const rr=rs.filter(r=>r.goal_id===g.id),completed=rr.filter(r=>r.status==='completed').length,p=rr.length?Math.round(completed/rr.length*100):0;return `<div class="barline"><b>${esc(g.name)}</b><div class="bar"><i style="width:${Math.min(p,100)}%"></i></div><strong>${p}%</strong></div>`}).join('')||'<p class="muted">Añade objetivos para ver estadísticas.</p>'}</div></div><div class="panel" style="margin-top:16px"><div class="section-head"><h3>Resumen</h3></div><table class="table"><tr><th>Indicador</th><th>Valor</th></tr><tr><td>Días registrados</td><td>${new Set(rs.map(r=>r.date)).size}</td></tr><tr><td>Registros completados</td><td>${rs.filter(r=>r.status==='completed').length}</td></tr><tr><td>Registros no aplicables</td><td>${rs.filter(r=>r.status==='na').length}</td></tr></table></div>`}
async function renderProfile(){const p=await profile();$('page-profile').innerHTML=`<div class="panel"><div class="section-head"><h3>Perfil</h3></div><div class="form-grid"><label>Usuario<input value="${esc(p.username)}" disabled></label><label>Correo<input value="${esc(p.email)}" disabled></label></div><p class="muted">Tu cuenta y tus objetivos están aislados de los demás usuarios.</p></div>`}
async function renderAdmin(){if(!(await isAdmin())){toast('Acceso no autorizado');showPage('home');return}const {data}=await sb.from('profiles').select('id,username,email,approved,created_at,role').neq('role','admin').order('created_at',{ascending:false});const rows=data||[];$('page-admin').innerHTML=`<div class="panel"><div class="section-head"><h3>Usuarios</h3><span class="muted">Aprobación de acceso</span></div>${rows.map(u=>`<div class="admin-card"><div><b>${esc(u.username)}</b><div class="muted">${esc(u.email)} · ${u.approved?'Aprobado':'Pendiente'}</div></div><div class="admin-actions">${!u.approved?`<button class="approve" onclick="setApproval('${u.id}',true)">Aceptar</button>`:`<button class="reject" onclick="setApproval('${u.id}',false)">Revocar</button>`}</div></div>`).join('')||'<p class="muted">No hay usuarios registrados.</p>'}</div>`}window.setApproval=async(id,approved)=>{const {error}=await sb.from('profiles').update({approved}).eq('id',id);if(error)toast(error.message);else{toast(approved?'Usuario aprobado':'Acceso revocado');renderAdmin()}}
boot();
